import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Main from "@/components/Main";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased h-full`}>
        <Main>{children}</Main>
      </body>
    </html>
  );
}
