export const FAKE_DATA_DB = [
  {
    _id: "65ef3f30675dde8010852df4",
    id: 12445,
    title: "Harry Potter and the Deathly Hallows: Part 2",
    vote_average: 8.105,
    vote_count: 19183,
    status: "Released",
    release_date: "2011-07-12T00:00:00.000Z",
    revenue: 1341511219,
    runtime: 130,
    adult: false,
    backdrop_path: "/n5A7brJCjejceZmHyujwUTVgQNC.jpg",
    budget: 125000000,
    homepage:
      "https://www.warnerbros.com/movies/harry-potter-and-deathly-hallows-part-2/",
    imdb_id: "tt1201607",
    original_language: "en",
    original_title: "Harry Potter and the Deathly Hallows: Part 2",
    overview:
      "Harry, Ron and Hermione continue their quest to vanquish the evil Voldemort once and for all. Just as things begin to look hopeless for the young wizards, Harry discovers a trio of magical objects that endow him with powers to rival Voldemort's formidable skills.",
    popularity: 110.974,
    poster_path:
      "https://image.tmdb.org/t/p/original//c54HpQmuwXjHq2C9wmoACjxoom3.jpg",
    tagline: "It all ends here.",
    genres: "Fantasy, Adventure",
    production_companies: "Warner Bros. Pictures, Heyday Films",
    production_countries: "United Kingdom, United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef41ac675dde80108c827f",
    id: 1201480,
    title: "Harry Potter and the Sorcerer's Stone (Extended Edition)",
    vote_average: 0,
    vote_count: 0,
    status: "Released",
    revenue: 1024000000,
    runtime: 159,
    adult: false,
    budget: 125000000,
    original_language: "en",
    original_title: "Harry Potter and the Sorcerer's Stone (Extended Edition)",
    overview:
      "Adaptation of the first of J.K. Rowling's popular children's novels about Harry Potter, a boy who learns on his eleventh birthday that he is the orphaned son of two powerful wizards and possesses unique magical powers of his own. He is summoned from his life as an unwanted child to become a student at Hogwarts, an English boarding school for wizards. There, he meets several friends who become his closest allies and help him discover the truth about his parents' mysterious deaths.",
    popularity: 0,
    tagline: "English",
  },
  {
    _id: "65ef3f30675dde8010852dcf",
    id: 671,
    title: "Harry Potter and the Philosopher's Stone",
    vote_average: 7.916,
    vote_count: 25379,
    status: "Released",
    release_date: "2001-11-16T00:00:00.000Z",
    revenue: 976475550,
    runtime: 152,
    adult: false,
    backdrop_path: "/hziiv14OpD73u9gAak4XDDfBKa2.jpg",
    budget: 125000000,
    homepage:
      "https://www.warnerbros.com/movies/harry-potter-and-sorcerers-stone/",
    imdb_id: "tt0241527",
    original_language: "en",
    original_title: "Harry Potter and the Philosopher's Stone",
    overview:
      "Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard—with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry. As he learns to harness his newfound powers with the help of the school's kindly headmaster, Harry uncovers the truth about his parents' deaths—and about the villain who's to blame.",
    popularity: 185.482,
    poster_path:
      "https://image.tmdb.org/t/p/original//wuMc08IPKEatf9rnMNXvIDxqP4W.jpg",
    tagline: "Let the magic begin.",
    genres: "Adventure, Fantasy",
    production_companies: "Warner Bros. Pictures, Heyday Films, 1492 Pictures",
    production_countries: "United Kingdom, United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f30675dde8010852e05",
    id: 12444,
    title: "Harry Potter and the Deathly Hallows: Part 1",
    vote_average: 7.763,
    vote_count: 17782,
    status: "Released",
    release_date: "2010-11-17T00:00:00.000Z",
    revenue: 954305868,
    runtime: 146,
    adult: false,
    backdrop_path: "/AqLcLsGGTzAjm3pCCq0CZCQrp6m.jpg",
    budget: 250000000,
    homepage:
      "https://www.warnerbros.com/movies/harry-potter-and-deathly-hallows-part-1/",
    imdb_id: "tt0926084",
    original_language: "en",
    original_title: "Harry Potter and the Deathly Hallows: Part 1",
    overview:
      "Harry, Ron and Hermione walk away from their last year at Hogwarts to find and destroy the remaining Horcruxes, putting an end to Voldemort's bid for immortality. But with Harry's beloved Dumbledore dead and Voldemort's unscrupulous Death Eaters on the loose, the world is more dangerous than ever.",
    popularity: 111.984,
    poster_path:
      "https://image.tmdb.org/t/p/original//iGoXIpQb7Pot00EEdwpwPajheZ5.jpg",
    tagline: "One Way… One Fate… One Hero.",
    genres: "Adventure, Fantasy",
    production_companies: "Warner Bros. Pictures, Heyday Films",
    production_countries: "United Kingdom, United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f30675dde8010852dfe",
    id: 675,
    title: "Harry Potter and the Order of the Phoenix",
    vote_average: 7.686,
    vote_count: 18177,
    status: "Released",
    release_date: "2007-07-08T00:00:00.000Z",
    revenue: 938212738,
    runtime: 138,
    adult: false,
    backdrop_path: "/pkxPkHOPJjOvzfQOclANEBT8OfK.jpg",
    budget: 150000000,
    homepage:
      "https://www.warnerbros.com/movies/harry-potter-and-order-phoenix/",
    imdb_id: "tt0373889",
    original_language: "en",
    original_title: "Harry Potter and the Order of the Phoenix",
    overview:
      "Returning for his fifth year of study at Hogwarts, Harry is stunned to find that his warnings about the return of Lord Voldemort have been ignored. Left with no choice, Harry takes matters into his own hands, training a small group of students to defend themselves against the dark arts.",
    popularity: 117.168,
    poster_path:
      "https://image.tmdb.org/t/p/original//5aOyriWkPec0zUDxmHFP9qMmBaj.jpg",
    tagline: "Evil Must Be Confronted.",
    genres: "Adventure, Fantasy",
    production_companies: "Warner Bros. Pictures, Heyday Films",
    production_countries: "United Kingdom, United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f30675dde8010852dff",
    id: 767,
    title: "Harry Potter and the Half-Blood Prince",
    vote_average: 7.697,
    vote_count: 18127,
    status: "Released",
    release_date: "2009-07-15T00:00:00.000Z",
    revenue: 933959197,
    runtime: 153,
    adult: false,
    backdrop_path: "/urDWNffjwmNi5IQaezw9GwqkUXa.jpg",
    budget: 250000000,
    homepage:
      "https://www.warnerbros.com/movies/harry-potter-and-half-blood-prince/",
    imdb_id: "tt0417741",
    original_language: "en",
    original_title: "Harry Potter and the Half-Blood Prince",
    overview:
      "As Lord Voldemort tightens his grip on both the Muggle and wizarding worlds, Hogwarts is no longer a safe haven. Harry suspects perils may even lie within the castle, but Dumbledore is more intent upon preparing him for the final battle fast approaching. Together they work to find the key to unlock Voldemorts defenses and to this end, Dumbledore recruits his old friend and colleague Horace Slughorn, whom he believes holds crucial information. Even as the decisive showdown looms, romance blossoms for Harry, Ron, Hermione and their classmates. Love is in the air, but danger lies ahead and Hogwarts may never be the same again.",
    popularity: 121.735,
    poster_path:
      "https://image.tmdb.org/t/p/original//z7uo9zmQdQwU5ZJHFpv2Upl30i1.jpg",
    tagline: "Dark Secrets Revealed",
    genres: "Adventure, Fantasy",
    production_companies: "Warner Bros. Pictures, Heyday Films",
    production_countries: "United Kingdom, United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f30675dde8010852df2",
    id: 674,
    title: "Harry Potter and the Goblet of Fire",
    vote_average: 7.816,
    vote_count: 19287,
    status: "Released",
    release_date: "2005-11-16T00:00:00.000Z",
    revenue: 895921036,
    runtime: 157,
    adult: false,
    backdrop_path: "/5rrGVmRUuCKVbqUu41XIWTXJmNA.jpg",
    budget: 150000000,
    homepage: "https://www.warnerbros.com/movies/harry-potter-and-goblet-fire/",
    imdb_id: "tt0330373",
    original_language: "en",
    original_title: "Harry Potter and the Goblet of Fire",
    overview:
      "When Harry Potter's name emerges from the Goblet of Fire, he becomes a competitor in a grueling battle for glory among three wizarding schools—the Triwizard Tournament. But since Harry never submitted his name for the Tournament, who did? Now Harry must confront a deadly dragon, fierce water demons and an enchanted maze only to find himself in the cruel grasp of He Who Must Not Be Named.",
    popularity: 134.276,
    poster_path:
      "https://image.tmdb.org/t/p/original//fECBtHlr0RB3foNHDiCBXeg9Bv9.jpg",
    tagline: "Dark And Difficult Times Lie Ahead.",
    genres: "Adventure, Fantasy",
    production_companies:
      "Warner Bros. Pictures, Heyday Films, Patalex IV Productions Limited",
    production_countries: "United Kingdom, United States of America",
    spoken_languages: "English, French",
  },
  {
    _id: "65ef3f30675dde8010852de5",
    id: 672,
    title: "Harry Potter and the Chamber of Secrets",
    vote_average: 7.721,
    vote_count: 20390,
    status: "Released",
    release_date: "2002-11-13T00:00:00.000Z",
    revenue: 876688482,
    runtime: 161,
    adult: false,
    backdrop_path: "/1stUIsjawROZxjiCMtqqXqgfZWC.jpg",
    budget: 100000000,
    homepage:
      "https://www.warnerbros.com/movies/harry-potter-and-chamber-secrets/",
    imdb_id: "tt0295297",
    original_language: "en",
    original_title: "Harry Potter and the Chamber of Secrets",
    overview:
      "Cars fly, trees fight back, and a mysterious house-elf comes to warn Harry Potter at the start of his second year at Hogwarts. Adventure and danger await when bloody writing on a wall announces: The Chamber Of Secrets Has Been Opened. To save Hogwarts will require all of Harry, Ron and Hermione’s magical abilities and courage.",
    popularity: 121.699,
    poster_path:
      "https://image.tmdb.org/t/p/original//sdEOH0992YZ0QSxgXNIGLq1ToUi.jpg",
    tagline: "Hogwarts is back in session.",
    genres: "Adventure, Fantasy",
    production_companies: "Warner Bros. Pictures, Heyday Films, 1492 Pictures",
    production_countries: "United Kingdom, United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f30675dde8010852dea",
    id: 673,
    title: "Harry Potter and the Prisoner of Azkaban",
    vote_average: 8.02,
    vote_count: 20038,
    status: "Released",
    release_date: "2004-05-31T00:00:00.000Z",
    revenue: 789804554,
    runtime: 141,
    adult: false,
    backdrop_path: "/obKmfNexgL4ZP5cAmzdL4KbHHYX.jpg",
    budget: 130000000,
    homepage:
      "https://www.warnerbros.com/movies/harry-potter-and-prisoner-azkaban/",
    imdb_id: "tt0304141",
    original_language: "en",
    original_title: "Harry Potter and the Prisoner of Azkaban",
    overview:
      "Year three at Hogwarts means new fun and challenges as Harry learns the delicate art of approaching a Hippogriff, transforming shape-shifting Boggarts into hilarity and even turning back time. But the term also brings danger: soul-sucking Dementors hover over the school, an ally of the accursed He-Who-Cannot-Be-Named lurks within the castle walls, and fearsome wizard Sirius Black escapes Azkaban. And Harry will confront them all.",
    popularity: 124.386,
    poster_path:
      "https://image.tmdb.org/t/p/original//aWxwnYoe8p2d2fcxOqtvAtJ72Rw.jpg",
    tagline: "Something wicked this way comes.",
    genres: "Adventure, Fantasy",
    production_companies:
      "Warner Bros. Pictures, 1492 Pictures, Heyday Films, P of A Productions Limited",
    production_countries: "United Kingdom, United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef41f8675dde80108d9f01",
    id: 1231220,
    title: "The Harry Potter IMAX Marathon",
    vote_average: 0,
    vote_count: 0,
    status: "Released",
    release_date: "2016-10-14T00:00:00.000Z",
    revenue: 67,
    runtime: 284,
    adult: false,
    backdrop_path: "/x5Pr77D2FfrtmNXsFZ9UQADfRol.jpg",
    budget: 500,
    original_language: "en",
    original_title: "The Harry Potter IMAX Marathon",
    overview:
      "A limited showing of the first Harry Potter Movie and The first Fantastic  Beasts movie in one showing",
    popularity: 0.6,
    poster_path:
      "https://image.tmdb.org/t/p/original//avA5fAcpLWDAXbV7A1qj6xacd60.jpg",
    tagline: "movie",
    genres: "Adventure, Fantasy",
    production_companies:
      "Warner Bros. Entertainment, Heyday Films, 1492 Pictures",
    production_countries: "United Kingdom",
  },
  {
    _id: "65ef3f32675dde8010853377",
    id: 899082,
    title: "Harry Potter 20th Anniversary: Return to Hogwarts",
    vote_average: 7.302,
    vote_count: 3084,
    status: "Released",
    release_date: "2022-01-01T00:00:00.000Z",
    revenue: 0,
    runtime: 103,
    adult: false,
    backdrop_path: "/8rft8A9nH43IReybFtYt21ezfMK.jpg",
    budget: 0,
    homepage:
      "https://www.hbomax.com/feature/urn:hbo:feature:GYbzrRAvf-ZPCKQEAAAAX",
    imdb_id: "tt16116174",
    original_language: "en",
    original_title: "Harry Potter 20th Anniversary: Return to Hogwarts",
    overview:
      "An enchanting making-of story told through all-new in-depth interviews and cast conversations, inviting fans on a magical first-person journey through one of the most beloved film franchises of all time.",
    popularity: 39.8,
    poster_path:
      "https://image.tmdb.org/t/p/original//jntLBq0MLR3hrwKaTQswxACRPMs.jpg",
    tagline: "Welcome back to where the magic began.",
    genres: "Documentary",
    production_companies:
      "Pulse Films, Warner Horizon Unscripted Television, Casey Patterson Entertainment",
    production_countries: "United Kingdom, United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f50675dde8010857180",
    id: 483898,
    title: "50 Greatest Harry Potter Moments",
    vote_average: 7.315,
    vote_count: 108,
    status: "Released",
    release_date: "2011-07-27T00:00:00.000Z",
    revenue: 0,
    runtime: 93,
    adult: false,
    backdrop_path: "/4LOxoeZWt5wr9mooxEZRFK96lDd.jpg",
    budget: 0,
    imdb_id: "tt2006673",
    original_language: "en",
    original_title: "50 Greatest Harry Potter Moments",
    overview:
      "To mark the release two weeks ago of the eighth and final movie in the series, Robbie Coltrane narrates a countdown of the movie franchise's best moments. From Harry's first meeting with Ron and Hermione aboard the Hogwarts Express through to magical mysteries.",
    popularity: 16.006,
    poster_path:
      "https://image.tmdb.org/t/p/original//g1xiBoLD6v3ZaXPa4QtuXiQeYKW.jpg",
    genres: "Documentary",
    production_companies: "Twenty Twenty Television, ITV",
    production_countries: "United Kingdom",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f56675dde8010857d6c",
    id: 482408,
    title: "Harry Potter: A History Of Magic",
    vote_average: 7.217,
    vote_count: 83,
    status: "Released",
    release_date: "2017-10-28T00:00:00.000Z",
    revenue: 0,
    runtime: 59,
    adult: false,
    backdrop_path: "/mjCYpJXCBYDZgMr1U1KZcFgFDfC.jpg",
    budget: 0,
    homepage: "http://www.bbc.co.uk/programmes/b09d5n6b",
    imdb_id: "tt7783322",
    original_language: "en",
    original_title: "Harry Potter: A History Of Magic",
    overview:
      "A thrilling journey through legends, belief and folklore, this film goes behind the scenes with the British Library as they search to tell that story through objects in their collection, in an ambitious new exhibition: Harry Potter: A History Of Magic.  J.K. Rowling, who is lending unseen manuscripts, drawings and drafts from her private archives (which will sit alongside treasures from the British Library, as well as original drafts and drawings from Jim Kay) talks about some of the personal items she has lent to the exhibition and gives new insight into her writing, looking at some of the objects from the exhibition that have fired her imagination.",
    popularity: 10.943,
    poster_path:
      "https://image.tmdb.org/t/p/original//geike7VgTrftxwzcvND4dRdZdAv.jpg",
    genres: "Documentary",
    production_companies: "BBC Studios Documentary Unit",
    production_countries: "United Kingdom",
    spoken_languages: "Spanish, English, Latin",
  },
  {
    _id: "65ef3f7c675dde801085de21",
    id: 919590,
    title: "Phantastische Harry Potter Momente - Das große SAT.1 Spezial",
    vote_average: 6.283,
    vote_count: 23,
    status: "Released",
    release_date: "2021-10-31T00:00:00.000Z",
    revenue: 0,
    runtime: 0,
    adult: false,
    budget: 0,
    original_language: "de",
    original_title:
      "Phantastische Harry Potter Momente - Das große SAT.1 Spezial",
    popularity: 8.436,
    poster_path:
      "https://image.tmdb.org/t/p/original//1Ci05BbrRgc8qwKSvliJH6gqzol.jpg",
    production_countries: "Germany",
    spoken_languages: "German",
  },
  {
    _id: "65ef3f80675dde801085e9d5",
    id: 116972,
    title: "Discovering the Real World of Harry Potter",
    vote_average: 6.5,
    vote_count: 21,
    status: "Released",
    release_date: "2001-12-10T00:00:00.000Z",
    revenue: 0,
    runtime: 72,
    adult: false,
    budget: 0,
    imdb_id: "tt0443483",
    original_language: "en",
    original_title: "Discovering the Real World of Harry Potter",
    overview:
      "Explore the myths and legends that inhabit the real world of Harry Potter. Follow award-winning documentary filmmakers as they offer insights to witches, wizards, Greek gods, ancient Celts, ghosts, magical creatures, alchemy, and ancient spells. Narrated by British actor Hugh Laurie, this fascinating documentary brings new dimensions to the historical and scientific world behind the Harry Potter series.",
    popularity: 2.488,
    poster_path:
      "https://image.tmdb.org/t/p/original//yLpnOqKw3ZycFu8t5Gil1BqTbnB.jpg",
    tagline: "As Seen On American Public Television",
    genres: "Family, Documentary",
    production_countries: "United Kingdom",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f82675dde801085ef7c",
    id: 918078,
    title: "Daniel Radcliffe: Being Harry Potter",
    vote_average: 6.1,
    vote_count: 20,
    status: "Released",
    release_date: "2012-10-10T00:00:00.000Z",
    revenue: 0,
    runtime: 42,
    adult: false,
    budget: 0,
    imdb_id: "tt2704274",
    original_language: "en",
    original_title: "Daniel Radcliffe: Being Harry Potter",
    overview:
      "BBC docuemntary about Daniel Radcliffe and his role as the main character in Harry potter",
    popularity: 4.998,
    poster_path:
      "https://image.tmdb.org/t/p/original//4keobTsQVrMS2JwE3TRod0SrYTD.jpg",
    genres: "Documentary",
  },
  {
    _id: "65ef3f85675dde801085f84f",
    id: 319391,
    title: "J.K. Rowling and the Birth of Harry Potter",
    vote_average: 6.8,
    vote_count: 19,
    status: "Released",
    release_date: "2004-12-07T00:00:00.000Z",
    revenue: 0,
    runtime: 60,
    adult: false,
    budget: 0,
    original_language: "en",
    original_title: "J.K. Rowling and the Birth of Harry Potter",
    overview:
      "In this fascinating (unauthorized) biographical documentary, you'll get the inside scoop on the creative force behind one of the greatest publishing phenomena in the last 100 years -- J.K. Rowling, author of the Harry Potter series of books. Explore Rowling's meteoric rise from obscurity into the ranks of the world's richest women (via her books), and visit the people and places that played a significant role in her life.",
    popularity: 3.948,
    poster_path:
      "https://image.tmdb.org/t/p/original//hY6Ndq1O4JiEngZ7xIOtcLUCDTX.jpg",
    genres: "Documentary",
    spoken_languages: "English",
  },
  {
    _id: "65ef3fa0675dde801086422d",
    id: 500008,
    title: "Harry Potter: The Making of Diagon Alley",
    vote_average: 4.4,
    vote_count: 11,
    status: "Released",
    release_date: "2014-06-30T00:00:00.000Z",
    revenue: 0,
    runtime: 43,
    adult: false,
    budget: 0,
    imdb_id: "tt5901980",
    original_language: "en",
    original_title: "Harry Potter: The Making of Diagon Alley",
    overview:
      "An inside look into the creation of Universal Studio's Diagon Alley attraction.",
    popularity: 1.814,
    genres: "Documentary",
    production_companies: "Peacock Productions",
  },
  {
    _id: "65ef3fa6675dde801086519e",
    id: 1082707,
    title: "The Magic Touch of Harry Potter",
    vote_average: 7.5,
    vote_count: 10,
    status: "Released",
    release_date: "2004-06-11T00:00:00.000Z",
    revenue: 0,
    runtime: 42,
    adult: false,
    budget: 0,
    original_language: "en",
    original_title: "The Magic Touch of Harry Potter",
    overview:
      "A 2004 documentary on the first three “Harry Potter” films detailing the behind-the-scenes journey of making them.",
    popularity: 7.528,
    poster_path:
      "https://image.tmdb.org/t/p/original//gwFARNYf1Odv3E8ESVHyikXmMIY.jpg",
    genres: "Documentary",
    spoken_languages: "English",
  },
  {
    _id: "65ef3fb5675dde80108673f5",
    id: 1039274,
    title: "Harry Potter: A Spirit Conspiracy?",
    vote_average: 6.3,
    vote_count: 9,
    status: "Released",
    release_date: "2005-09-22T00:00:00.000Z",
    revenue: 0,
    runtime: 100,
    adult: false,
    budget: 0,
    original_language: "en",
    original_title: "Harry Potter: A Spirit Conspiracy?",
    overview:
      "The Occult Agenda documentary series is designed to awaken the church and non-believers alike to the spiritual warfare happening in the world today. Part I focuses on the Harry Potter phenomenon that has swept the world since author J.K. Rowling introduced her best-selling book series. But is Potter-mania merely the result of imaginative writing and clever marketing? Or could there be a hidden power behind the craze that has cast a spell on adults and children alike?",
    popularity: 3.219,
    poster_path:
      "https://image.tmdb.org/t/p/original//e8jvqpVbVeVlSOV216sOIZmykGA.jpg",
    tagline: "The Occult Agenda: Part 1",
    genres: "Documentary",
    production_companies: "Good Fight Ministries, Adullam Films LLC",
    spoken_languages: "English",
  },
];

export const sortMovies = (movies: any[]) => {
  return [...movies].sort((a: any, b: any) => b.popularity - a.popularity);
};

// TODO: Fetch directly from the server

export const getMovie = (movies: any[], title: string) => {
  return (
    movies.find((movie: any) => movie.imdb_id == title.toLowerCase()) || {}
  );
};
