export const FAKE_DATA_DB = [
  {
    _id: "65ef3f30675dde8010852dc4",
    id: 27205,
    title: "Inception",
    vote_average: 8.364,
    vote_count: 34495,
    status: "Released",
    release_date: "2010-07-15T00:00:00.000Z",
    revenue: 825532764,
    runtime: 148,
    adult: false,
    backdrop_path: "/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
    budget: 160000000,
    homepage: "https://www.warnerbros.com/movies/inception",
    imdb_id: "tt1375666",
    original_language: "en",
    original_title: "Inception",
    overview:
      "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.",
    popularity: 83.952,
    poster_path:
      "https://image.tmdb.org/t/p/original//oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    tagline: "Your mind is the scene of the crime.",
    genres: "Action, Science Fiction, Adventure",
    production_companies: "Legendary Pictures, Syncopy, Warner Bros. Pictures",
    production_countries: "United Kingdom, United States of America",
    spoken_languages: "English, French, Japanese, Swahili",
  },
  {
    _id: "65ef3f6d675dde801085b984",
    id: 613092,
    title: "The Crack: Inception",
    vote_average: 6.7,
    vote_count: 34,
    status: "Released",
    release_date: "2019-10-04T00:00:00.000Z",
    revenue: 332356,
    runtime: 117,
    adult: false,
    backdrop_path: "/JeGkRdNsOuMrgwBdtB0hp763MU.jpg",
    budget: 0,
    homepage: "https://filmaxinternationalsales.com/film/the-crack-inception",
    imdb_id: "tt6793710",
    original_language: "es",
    original_title: "El crack cero",
    overview:
      "Madrid, Spain, 1975; shortly after the end of the Franco dictatorship. Six months after the mysterious death of his lover, a prestigious tailor, a married woman visits the office of the young Germán Areta, a former police officer turned private detective, to request his professional services.",
    popularity: 3.408,
    poster_path:
      "https://image.tmdb.org/t/p/original//kzgPu2CMxBr4YZZxC1Off4cUfR9.jpg",
    tagline: "The prequel to the cult film El Crack",
    genres: "Drama, Thriller",
    production_companies: "TVE, Movistar+, Trece TV, Nickel Odeon",
    production_countries: "Spain",
    spoken_languages: "Spanish",
  },
  {
    _id: "65ef3f44675dde8010855180",
    id: 64956,
    title: "Inception: The Cobol Job",
    vote_average: 7.255,
    vote_count: 290,
    status: "Released",
    release_date: "2010-12-07T00:00:00.000Z",
    revenue: 0,
    runtime: 14,
    adult: false,
    budget: 0,
    imdb_id: "tt5295894",
    original_language: "en",
    original_title: "Inception: The Cobol Job",
    overview:
      'This "Inception" prequel unfolds courtesy of a beautiful Motion Comic, and explains how Cobb, Arthur and Nash were enlisted by Cobol Engineering.',
    popularity: 8.355,
    poster_path:
      "https://image.tmdb.org/t/p/original//sNxqwtyHMNQwKWoFYDqcYTui5Ok.jpg",
    genres: "Animation, Action, Thriller, Science Fiction",
    production_companies: "Warner Bros. Pictures, Warner Home Video",
    production_countries: "United Kingdom, United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3fdd675dde801086e334",
    id: 250845,
    title: "WWA The Inception",
    vote_average: 3.1,
    vote_count: 5,
    status: "Released",
    release_date: "2001-10-26T00:00:00.000Z",
    revenue: 0,
    runtime: 0,
    adult: false,
    budget: 0,
    imdb_id: "tt0311992",
    original_language: "en",
    original_title: "WWA The Inception",
    overview:
      'The first World Wrestling Allstars pay per view, live from Sydney, Australia! A tournament titled "7 Deadly Sins", each round having a stipulation match, the winner will be crowned the first ever WWA Heavyweight Champion! Wrestlers such as Jeff Jarrett, Road Dogg, Jerry Lawler all compete in the tournament, with the WWA Commissioner, Bret Hart not too far away to make sure nothing gets to far out of hand!',
    popularity: 1.88,
  },
  {
    _id: "65ef4012675dde80108777fd",
    id: 350632,
    title: "The Inception of Dramatic Representation",
    vote_average: 5.8,
    vote_count: 3,
    status: "Released",
    revenue: 0,
    runtime: 83,
    adult: false,
    budget: 0,
    homepage:
      "http://onlinebharatanatyam.com/2013/11/17/dvd-natyarambham-learning-adavus-in-bharatanatyam/",
    original_language: "en",
    original_title: "Nātyārambham",
    overview:
      "On certain Adavus: the basic steps in Bharatanatyam. The first part covers Tatta Adavu, Natta Adavu, Visharu Adavu , Tatti Metti Adavu and Teermanam Adavu.",
    popularity: 0.68,
    tagline: "Learning Adavus in Bharatanatyam - Part 1",
    spoken_languages: "English, Sanskrit",
  },
  {
    _id: "65ef4057675dde8010883093",
    id: 957443,
    title: "Inception: Jump Right Into the Action",
    vote_average: 9.5,
    vote_count: 2,
    status: "Released",
    revenue: 0,
    runtime: 44,
    adult: false,
    budget: 0,
    imdb_id: "tt5295990",
    original_language: "en",
    original_title: "Inception: Jump Right Into the Action",
    overview:
      "Inception: Making of. Join filmmaker Christopher Nolan and his cast and crew as they reveal the secrets of Inception, its development, characters, performances, story and jaw-dropping special effects in this solid 14-segments piece.",
    popularity: 0.6,
    spoken_languages: "English",
  },
  {
    _id: "65ef407d675dde8010889e6e",
    id: 973484,
    title: "Inception: Music from the Motion Picture",
    vote_average: 6,
    vote_count: 1,
    status: "Released",
    release_date: "2010-12-07T00:00:00.000Z",
    revenue: 0,
    runtime: 38,
    adult: false,
    budget: 0,
    original_language: "en",
    original_title: "Inception: Music from the Motion Picture",
    overview:
      "The Special Features Blu-ray disc contains a lossless DTS-HD MA 5.1 surround mix of the Inception soundtrack.",
    popularity: 1.013,
    poster_path:
      "https://image.tmdb.org/t/p/original//7uM4DyRVAcgagvhZoWrkrqMPbqV.jpg",
    genres: "Music",
  },
  {
    _id: "65ef40ca675dde8010898a60",
    id: 542438,
    title: "Bikini Inception",
    vote_average: 7,
    vote_count: 1,
    status: "Released",
    release_date: "2015-05-19T00:00:00.000Z",
    revenue: 0,
    runtime: 106,
    adult: false,
    budget: 0,
    imdb_id: "tt8269586",
    original_language: "en",
    original_title: "Bikini Inception",
    overview:
      "Two flunky Janitors in an Arctic Lab perform unauthorized experiments transporting them to a beach dream world in Malibu California w/50 beautiful young girls and a female Brazilian PhD Student wearing only a bra and panties. A '67 Muscle car races chases horses guns fights surfing, sumo wrestler, wolf monster, underwater scenes tons of gorgeous models. Sexy sci-fi fun.",
    popularity: 1.328,
    poster_path:
      "https://image.tmdb.org/t/p/original//mNASlEOFX2c9upxaSbgeKFvIr1L.jpg",
    genres: "Comedy",
    production_companies: "Luck Films",
    spoken_languages: "English",
  },
  {
    _id: "65ef415b675dde80108b64ed",
    id: 887291,
    title: "L’inceppata",
    vote_average: 0,
    vote_count: 0,
    status: "Released",
    release_date: "1960-10-01T00:00:00.000Z",
    revenue: 0,
    runtime: 11,
    adult: false,
    budget: 0,
    original_language: "en",
    original_title: "L’inceppata",
    overview:
      "A village in Calabria still follows ancient customs in which young women must secretly wait for a log to be dragged to their doorstep in a symbolic declaration of love. Lino Del Fra reflects on how the weight of traditions exercises social control over love and family relationships.",
    popularity: 0.6,
    genres: "Documentary",
  },
  {
    _id: "65ef4194675dde80108c2b0b",
    id: 973810,
    title: "Palestrina - Princeps musicae",
    vote_average: 0,
    vote_count: 0,
    status: "Released",
    release_date: "2009-11-15T00:00:00.000Z",
    revenue: 0,
    runtime: 52,
    adult: false,
    budget: 0,
    imdb_id: "tt1611965",
    original_language: "en",
    original_title: "Palestrina - Princeps musicae",
    overview:
      "A music film on the life of Giovanni Pierluigi da Palestrina, a famous Italian Renaissance composer of sacred music and the best-known 16th-century composer of the Roman School.",
    popularity: 0.6,
    poster_path:
      "https://image.tmdb.org/t/p/original//sbfc2auLYBWzibcE6YtMrBEKofD.jpg",
  },
];
